# Resources/config/services.yml
services:

    webeweb.bundle.jquery.querybuilderbundle.twig.extension.querybuilder:
        class:     WBW\Bundle\JQuery\QueryBuilderBundle\Twig\Extension\QueryBuilderTwigExtension
        arguments: ["@=service('kernel').locateResource('@JQueryQueryBuilderBundle')", "%kernel.environment%"]
        tags:
          - { name: twig.extension }
